# Generated by Django 5.1.4 on 2024-12-04 20:09

import comment.utils
import comment.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0003_comment_attached_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="attached_fild",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=comment.utils.comment_text_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["txt"]
                    ),
                    comment.validators.validate_file_size,
                ],
            ),
        ),
    ]
