# Generated by Django 5.1.4 on 2024-12-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0004_comment_attached_fild"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="attached_fild",
            new_name="attached_field",
        ),
    ]
