# Generated by Django 5.1.4 on 2024-12-04 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0005_rename_attached_fild_comment_attached_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="attached_field",
            new_name="attached_file",
        ),
    ]
